ALTER TABLE mascotas ADD COLUMN microchip VARCHAR(50);
ALTER TABLE facturas ADD COLUMN total_pagado DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE facturas ADD COLUMN saldo_pendiente DOUBLE PRECISION DEFAULT 0.0;