"""
Seed script for catalogo_servicios table.
Idempotent: skips if the table already has rows.

Run from project root:
    python backend/scripts/seed_catalogo.py
Or inside Docker:
    python /app/scripts/seed_catalogo.py
"""
import sys
import os
from dotenv import load_dotenv

# Add /app (Docker) or backend/ (local) to path
sys.path.insert(0, "/app")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

load_dotenv()

from app.core.database import SessionLocal
from app.models.models import CatalogoServicio

# (nombre, categoria, precio_ref, unidad)
SERVICIOS = [
    # ADMINISTRACION VARIOS
    ("FLK", "ADMINISTRACION VARIOS", 80.0, "AMIVETS"),
    ("SERVICIO DE MENSAJERIA", "ADMINISTRACION VARIOS", 10.0, "ADMINISTRACION"),

    # CONSULTA
    ("CONSULTA CAMADA", "CONSULTA", 55.0, "VETERINARIA"),
    ("CONSULTA CARDIOLOGICA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA DERMATOLOGICA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA EMERGENCIA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA ESPECIALIZADA", "CONSULTA", 70.0, "AMIVETS"),
    ("CONSULTA FELINA", "CONSULTA", 50.0, "VETERINARIA"),
    ("CONSULTA GENERAL", "CONSULTA", 40.0, "VETERINARIA"),
    ("CONSULTA NEFROLOGICA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA NEUROINMUNOFARMACOLOGICA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA NEUROLOGICA", "CONSULTA", 90.0, "VETERINARIA"),
    ("CONSULTA ODONTOLOGICA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA OFTALMOLOGICA", "CONSULTA", 100.0, "VETERINARIA"),
    ("CONSULTA ONCOLOGICA", "CONSULTA", 70.0, "VETERINARIA"),
    ("CONSULTA ONCOLOGICA COMUNITARIA", "CONSULTA", 20.0, "VETERINARIA"),
    ("CONSULTA ONCOLOGICA CONTROL", "CONSULTA", 40.0, "VETERINARIA"),
    ("CONSULTA ONCOLOGICA ESPECIAL", "CONSULTA", 40.0, "VETERINARIA"),
    ("CONSULTA REVISION", "CONSULTA", 30.0, "VETERINARIA"),
    ("CONSULTA TRAUMATOLOGICA", "CONSULTA", 80.0, "VETERINARIA"),
    ("CONTROL TRAUMATOLOGICO", "CONSULTA", 60.0, "VETERINARIA"),
    ("ECOGRAFIA DE TORAX", "CONSULTA", 45.0, "AMIVETS"),
    ("EUTANASIA RAZA PEQUEÑA (HASTA 15 KILOS)", "CONSULTA", 110.0, "PROCEDIMIENTOS"),
    ("EUTANASIA RAZAS GRANDES (30 KILOS EN ADELANTE)", "CONSULTA", 140.0, "PROCEDIMIENTOS"),
    ("EUTANASIA RAZAS MEDIANAS (DE 15 A 30 KILOS)", "CONSULTA", 120.0, "PROCEDIMIENTOS"),
    ("EVALUACION CARDIOLOGICA", "CONSULTA", 145.0, "IMAGENOLOGIA"),
    ("FISIOTERAPIA", "CONSULTA", 70.0, "PROCEDIMIENTOS"),
    ("MEDICINA DEL DOLOR", "CONSULTA", 70.0, "CONSULTA"),
    ("PIPETAS", "CONSULTA", 25.0, "PRODUCTO"),
    ("QUIMIOTERAPIA", "CONSULTA", 50.0, "PROCEDIMIENTOS"),
    ("QUIMIOTERAPIA COMUNITARIA", "CONSULTA", 20.0, "PROCEDIMIENTOS"),
    ("TEST DE FLUORESCEINA", "CONSULTA", 15.0, "PROCEDIMIENTOS"),
    ("TOMA DE MUESTRA", "CONSULTA", 10.0, "PROCEDIMIENTOS"),

    # FARMACIA
    ("AMPICILINA SULBACTAM", "FARMACIA", 10.0, "MEDICINAS"),
    ("ARTROSAN", "FARMACIA", 60.0, "MEDICINAS"),
    ("CERENIA", "FARMACIA", 5.0, "MEDICINAS"),
    ("CITARABINA", "FARMACIA", 35.0, "MEDICINAS"),
    ("DEXMEDETOMIDINA", "FARMACIA", 15.0, "MEDICINAS"),
    ("FARMACOS", "FARMACIA", 20.0, "MEDICINAS"),
    ("LIDOCAINA", "FARMACIA", 5.0, "MEDICINAS"),
    ("MECTAL 1980MG", "FARMACIA", 10.0, "MEDICINAS"),
    ("MECTAL 660MG", "FARMACIA", 10.0, "MEDICINAS"),

    # HOSPITALIZACION
    ("ALIMENTO PENSIONADOS - HOSPITALIZADOS", "HOSPITALIZACION", 5.0, "HOSPITALIZACION"),
    ("ANESTESIA", "HOSPITALIZACION", 50.0, "PROCEDIMIENTOS"),
    ("APLICACION DE OSURNIA", "HOSPITALIZACION", 35.0, "TRATAMIENTO"),
    ("ASISTENTE DE EMERGENCIA", "HOSPITALIZACION", 30.0, "HONORARIO"),
    ("BOMBA DE INFUSION", "HOSPITALIZACION", 15.0, "USO DE EQUIPO"),
    ("BURETA 150 ML", "HOSPITALIZACION", 3.0, "MATERIAL MEDICO"),
    ("CAVITRON DENTAL", "HOSPITALIZACION", 20.0, "EQUIPO MEDICO"),
    ("COMPRESA", "HOSPITALIZACION", 5.0, "MATERIAL MEDICO"),
    ("CONVENIA", "HOSPITALIZACION", 40.0, "MEDICINA"),
    ("CUIDADO MEDICO DIURNO", "HOSPITALIZACION", 30.0, "HOSPITALIZACION"),
    ("CUIDADO MEDICO NOCTURNO", "HOSPITALIZACION", 40.0, "HOSPITALIZACION"),
    ("CURA DE HERIDA", "HOSPITALIZACION", 10.0, "PROCEDIMIENTOS"),
    ("CURA DE MIASIS", "HOSPITALIZACION", 15.0, "PROCEDIMIENTOS"),
    ("CURA DE SUEÑO", "HOSPITALIZACION", 30.0, "PROCEDIMIENTOS"),
    ("CURVA DE GLICEMIA", "HOSPITALIZACION", 15.0, "LABORATORIO"),
    ("DEXMEDETOMIDINA (HOSP.)", "HOSPITALIZACION", 15.0, "MEDICINA"),
    ("DRENAJE DEL TORAX", "HOSPITALIZACION", 50.0, "PROCEDIMIENTOS"),
    ("ELECTROBISTURI", "HOSPITALIZACION", 5.0, "PROCEDIMIENTOS"),
    ("ENEMA", "HOSPITALIZACION", 100.0, "HOSPITALIZACION"),
    ("ENFERMERIA DIURNA", "HOSPITALIZACION", 10.0, "HOSPITALIZACION"),
    ("ENFERMERIA NOCTURNA", "HOSPITALIZACION", 15.0, "PROCEDIMIENTOS"),
    ("ENFERMERO CIRCULANTE", "HOSPITALIZACION", 10.0, "PROCEDIMIENTOS"),
    ("FLUIDOTERAPIA", "HOSPITALIZACION", 30.0, "TRATAMIENTO"),
    ("HONORARIO 2", "HOSPITALIZACION", 100.0, "HONORARIO MEDICO"),
    ("HONORARIO ANESTESIOLOGO", "HOSPITALIZACION", 100.0, "HONORARIO MEDICO"),
    ("HONORARIO CRIOCIRUGIA", "HOSPITALIZACION", 60.0, "HONORARIO MEDICO"),
    ("HONORARIO ELECTROPORACION", "HOSPITALIZACION", 200.0, "HONORARIO MEDICO"),
    ("HONORARIOS TRANSFUSION", "HOSPITALIZACION", 60.0, "HONORARIO MEDICO"),
    ("HOSPEDAJE FELINO + MEDICINAS", "HOSPITALIZACION", 30.0, "AMIVETS"),
    ("HOSPITALIZACION", "HOSPITALIZACION", 40.0, "AMIVETS"),
    ("IMPLANTACION DE CHIP", "HOSPITALIZACION", 30.0, "PROCEDIMIENTOS"),
    ("INFERVAC", "HOSPITALIZACION", 10.0, "AMIVETS"),
    ("INFUSION DE PROPOFOL", "HOSPITALIZACION", 15.0, "VETERINARIA"),
    ("KIT DE TOMA DE MUESTRA", "HOSPITALIZACION", 10.0, "AMIVETS"),
    ("KIT DE VIA", "HOSPITALIZACION", 10.0, "AMIVETS"),
    ("MAQUINA DE ANESTESIA", "HOSPITALIZACION", 25.0, "PROCEDIMIENTOS"),
    ("METADOL", "HOSPITALIZACION", 5.0, "PROCEDIMIENTOS"),
    ("MONITOR MULTIPARAMETROS", "HOSPITALIZACION", 20.0, "PROCEDIMIENTOS"),
    ("OMEPRAZOL", "HOSPITALIZACION", 2.0, "PROCEDIMIENTOS"),
    ("OXIGENO", "HOSPITALIZACION", 50.0, "AMIVETS"),
    ("SEDACION", "HOSPITALIZACION", 30.0, "AMIVETS"),
    ("SNAP", "HOSPITALIZACION", 35.0, "AMIVETS"),
    ("SOLUCION RINGER LACTATO", "HOSPITALIZACION", 8.0, "PROCEDIMIENTOS"),
    ("SONDA DE ALIMENTACION", "HOSPITALIZACION", 120.0, "AMIVETS"),
    ("SONDA DE OXIGENO", "HOSPITALIZACION", 20.0, "ADMINISTRACION"),
    ("SONDA NASOGASTRICA 8", "HOSPITALIZACION", 120.0, "AMIVETS"),
    ("SONDA URINARIA", "HOSPITALIZACION", 50.0, "PROCEDIMIENTOS"),
    ("SONDAJE", "HOSPITALIZACION", 90.0, "PROCEDIMIENTOS"),
    ("SONDAJE URETRAL", "HOSPITALIZACION", 50.0, "PROCEDIMIENTOS"),
    ("TRATAMIENTO INYECTADO MAS DE 20 KILOS", "HOSPITALIZACION", 15.0, "TRATAMIENTO"),
    ("TRATAMIENTO INYECTADO MENOS 20 KILOS", "HOSPITALIZACION", 10.0, "TRATAMIENTO"),
    ("TUBO DE ALIMENTACION", "HOSPITALIZACION", 80.0, "PROCEDIMIENTOS"),
    ("TUBO NASO - GASTRICO", "HOSPITALIZACION", 120.0, "PROCEDIMIENTOS"),

    # IMAGENOLOGIA
    ("ECOCARDIOGRAMA", "IMAGENOLOGIA", 50.0, "IMAGENOLOGIA"),
    ("ECOGRAFIA ABDOMINAL", "IMAGENOLOGIA", 50.0, "IMAGENOLOGIA"),
    ("ELECTROCARDIOGRAMA", "IMAGENOLOGIA", 30.0, "IMAGENOLOGIA"),
    ("INFORME RADIOLOGICO", "IMAGENOLOGIA", 50.0, "IMAGENOLOGIA"),
    ("TOMOGRAFIA CON CONTRASTE", "IMAGENOLOGIA", 500.0, "IMAGENOLOGIA"),
    ("TOMOGRAFIA SIMPLE", "IMAGENOLOGIA", 450.0, "IMAGENOLOGIA"),

    # LABORATORIO
    ("AMILASA", "LABORATORIO", 30.0, "AMIVETS"),
    ("BIOPSIA M&S", "LABORATORIO", 140.0, "VETERINARIA"),
    ("CALCIO EN SANGRE", "LABORATORIO", 60.0, "AMIVETS"),
    ("CITOLOGIA M&S", "LABORATORIO", 80.0, "VETERINARIA"),
    ("CITOLOGIA VAGINAL", "LABORATORIO", 20.0, "PROCEDIMIENTOS"),
    ("CITOLOGIAS AMIVETS", "LABORATORIO", 20.0, "VETERINARIA"),
    ("COPROLOGIA AMIVETS", "LABORATORIO", 20.0, "VETERINARIA"),
    ("CORTISOL", "LABORATORIO", 150.0, "PROCEDIMIENTOS"),
    ("CULTIVO Y ANTIBIOGRAMA LA", "LABORATORIO", 75.0, "VETERINARIA"),
    ("CULTIVO Y ANTIBIOGRAMA LD", "LABORATORIO", 75.0, "VETERINARIA"),
    ("ELECTROLITOS", "LABORATORIO", 30.0, "AMIVETS"),
    ("ENVIO DE MUESTRA", "LABORATORIO", 3.0, "PROCEDIMIENTOS"),
    ("ESTIMACION DE OVULACION", "LABORATORIO", 20.0, "PROCEDIMIENTOS"),
    ("FENOBARBITAL EN SANGRE", "LABORATORIO", 50.0, "AMIVETS"),
    ("HEMATOLOGIA", "LABORATORIO", 35.0, "VETERINARIA"),
    ("HEMATOLOGIA - LC", "LABORATORIO", 30.0, "AMIVETS"),
    ("HEMATOLOGIA + INDICE RENAL", "LABORATORIO", 40.0, "ADMINISTRACION"),
    ("HEMATOLOGIA ESPECIAL ZL", "LABORATORIO", 150.0, "VETERINARIA"),
    ("HEMATOLOGIA LA", "LABORATORIO", 30.0, "VETERINARIA"),
    ("HEMATOLOGIA LD", "LABORATORIO", 30.0, "VETERINARIA"),
    ("HEMATOLOGIA LH", "LABORATORIO", 30.0, "VETERINARIA"),
    ("HEMOCULTIVO", "LABORATORIO", 115.0, "VETERINARIA"),
    ("INMUNOHISTOQUIMICA M&S", "LABORATORIO", 220.0, "VETERINARIA"),
    ("KIT TOMA DE MUESTRA", "LABORATORIO", 10.0, "AMIVETS"),
    ("LIMPIEZA DENTAL FELINA", "LABORATORIO", 195.0, "AMIVETS"),
    ("LIPASA", "LABORATORIO", 40.0, "AMIVETS"),
    ("P4 PROGESTERONA", "LABORATORIO", 70.0, "PROCEDIMIENTOS"),
    ("PCR - BABESIA", "LABORATORIO", 120.0, "VETERINARIA"),
    ("PCR - DISTEMPER", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR - EHRLICHIA/ANAPLASMA", "LABORATORIO", 45.0, "VETERINARIA"),
    ("PCR - HEMOPARASITOS 1 - CANINO", "LABORATORIO", 125.0, "VETERINARIA"),
    ("PCR - HEMOPARASITOS 2 - CANINO", "LABORATORIO", 195.0, "VETERINARIA"),
    ("PCR - HEPATOZOON CANIS", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR - HERPES FELINO", "LABORATORIO", 110.0, "AMIVETS"),
    ("PCR - LEISHMANIA", "LABORATORIO", 120.0, "VETERINARIA"),
    ("PCR - MULTIPLEX FELINO 1 (SIDA Y LEUCEMIA)", "LABORATORIO", 130.0, "VETERINARIA"),
    ("PCR - MULTIPLEX FELINO 2", "LABORATORIO", 185.0, "VETERINARIA"),
    ("PCR - MULTIPLEX FELINO 3", "LABORATORIO", 185.0, "VETERINARIA"),
    ("PCR - MULTIPLEX FELINO 4", "LABORATORIO", 125.0, "VETERINARIA"),
    ("PCR - MULTIPLEX FELINO 5", "LABORATORIO", 110.0, "AMIVETS"),
    ("PCR - MYCOPLASMA", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR - PANLEUCOPENIA", "LABORATORIO", 110.0, "AMIVETS"),
    ("PCR - PAPILOMA FELINO", "LABORATORIO", 100.0, "AMIVETS"),
    ("PCR - PARVOVIRUS", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR - PIF", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR - TOXOPLASMA GONDII", "LABORATORIO", 115.0, "PROCEDIMIENTOS"),
    ("PCR - TRIPANOSOMA", "LABORATORIO", 105.0, "VETERINARIA"),
    ("PCR- BORDETELLA", "LABORATORIO", 110.0, "AMIVETS"),
    ("PCR DE BRUCELLA", "LABORATORIO", 115.0, "ADMINISTRACION"),
    ("PCR DIROFILARIA", "LABORATORIO", 110.0, "AMIVETS"),
    ("PCR LEUCEMIA", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR MULTIPLEX FELINO 6", "LABORATORIO", 225.0, "AMIVETS"),
    ("PCR-MULTIPLEX FELINO 8", "LABORATORIO", 110.0, "VETERINARIA"),
    ("PCR -LEPTOSPIRA SSP", "LABORATORIO", 120.0, "AMIVETS"),
    ("PERFIL HEPATICO", "LABORATORIO", 20.0, "AMIVETS"),
    ("PERFIL RENAL LA", "LABORATORIO", 65.0, "VETERINARIA"),
    ("PERFIL VETERINARIO", "LABORATORIO", 80.0, "VETERINARIA"),
    ("PERFIL VETERINARIO LA", "LABORATORIO", 65.0, "VETERINARIA"),
    ("PERFIL VETERINARIO (DONANTES)", "LABORATORIO", 65.0, "PROCEDIMIENTOS"),
    ("PERFIL VETERINARIO B", "LABORATORIO", 65.0, "VETERINARIA"),
    ("PERFIL VETERINARIO EXTERNO", "LABORATORIO", 65.0, "VETERINARIA"),
    ("PERFIL VETERINARIO LC", "LABORATORIO", 65.0, "AMIVETS"),
    ("PERFIL VETERINARIO LD", "LABORATORIO", 65.0, "VETERINARIA"),
    ("PERFIL VETERINARIO LH", "LABORATORIO", 65.0, "VETERINARIA"),
    ("PROTEINAS TOTAL Y FRACCIONADA - LD", "LABORATORIO", 10.0, "AMIVETS"),
    ("PT / PTT", "LABORATORIO", 60.0, "VETERINARIA"),
    ("QUIMICA", "LABORATORIO", 50.0, "VETERINARIA"),
    ("RASPADO DE PIEL", "LABORATORIO", 15.0, "VETERINARIA"),
    ("RAYOS X", "LABORATORIO", 85.0, "VETERINARIA"),
    ("SDMA", "LABORATORIO", 50.0, "VETERINARIA"),
    ("SERVICIO DE ENVIO DE MUESTRA", "LABORATORIO", 20.0, "AMIVETS"),
    ("T4", "LABORATORIO", 50.0, "VETERINARIA"),
    ("TOMA DE BIOPSIA M&S", "LABORATORIO", 40.0, "PROCEDIMIENTOS"),
    ("TOMA DE CITOLOGIA", "LABORATORIO", 10.0, "PROCEDIMIENTOS"),
    ("TSH", "LABORATORIO", 50.0, "VETERINARIA"),
    ("UPC", "LABORATORIO", 30.0, "AMIVETS"),
    ("UROANALISIS AVILAB", "LABORATORIO", 20.0, "VETERINARIA"),
    ("UROANALISIS - CORONA", "LABORATORIO", 20.0, "VETERINARIA"),
    ("UROANALISIS DUOLAB", "LABORATORIO", 20.0, "VETERINARIA"),
    ("UROANALISIS HUELLAS", "LABORATORIO", 20.0, "VETERINARIA"),
    ("UROCULTIVO AVILAB", "LABORATORIO", 60.0, "VETERINARIA"),
    ("UROCULTIVO DUOLAB", "LABORATORIO", 60.0, "VETERINARIA"),

    # PELUQUERIA
    ("BAÑOS - COSMETICOS RAZAS GRANDES - CANINO", "PELUQUERIA", 50.0, "VETERINARIA"),
    ("BAÑOS - COSMETICOS RAZAS MEDIANAS - CANINO", "PELUQUERIA", 35.0, "VETERINARIA"),
    ("BAÑOS - COSMETICOS RAZAS MEDIANAS - FELINO", "PELUQUERIA", 30.0, "VETERINARIA"),
    ("BAÑOS - COSMETICOS RAZAS PEQUEÑAS - CANINO", "PELUQUERIA", 25.0, "VETERINARIA"),
    ("BAÑOS - COSMETICOS RAZAS PEQUEÑAS - FELINO", "PELUQUERIA", 20.0, "VETERINARIA"),
    ("BAÑOS MEDICADOS RAZAS GRANDES - CANINO", "PELUQUERIA", 55.0, "VETERINARIA"),
    ("BAÑOS MEDICADOS RAZAS MEDIANAS - CANINO", "PELUQUERIA", 40.0, "VETERINARIA"),
    ("BAÑOS MEDICADOS RAZAS MEDIANAS - FELINO", "PELUQUERIA", 35.0, "VETERINARIA"),
    ("BAÑOS MEDICADOS RAZAS PEQUEÑAS - CANINO", "PELUQUERIA", 30.0, "VETERINARIA"),
    ("BAÑOS MEDICADOS RAZAS PEQUEÑAS - FELINO", "PELUQUERIA", 25.0, "VETERINARIA"),
    ("CORTE DE UÑAS RAZAS GRANDES - CANINO", "PELUQUERIA", 10.0, "VETERINARIA"),
    ("CORTE DE UÑAS RAZAS MEDIANAS - CANINO", "PELUQUERIA", 10.0, "VETERINARIA"),
    ("CORTE DE UÑAS RAZAS MEDIANAS - FELINO", "PELUQUERIA", 15.0, "VETERINARIA"),
    ("CORTE DE UÑAS RAZAS PEQUEÑAS - CANINO", "PELUQUERIA", 10.0, "VETERINARIA"),
    ("CORTE DE UÑAS RAZAS PEQUEÑAS - FELINO", "PELUQUERIA", 15.0, "VETERINARIA"),
    ("LIMPIEZA DE OIDO", "PELUQUERIA", 10.0, "AMIVETS"),
    ("PELUQUERIA - COSMETICA RAZAS GRANDES - CANINO", "PELUQUERIA", 100.0, "VETERINARIA"),
    ("PELUQUERIA - COSMETICA RAZAS MEDIANAS - CANINO", "PELUQUERIA", 60.0, "VETERINARIA"),
    ("PELUQUERIA - COSMETICA RAZAS PEQUEÑAS - CANINO", "PELUQUERIA", 40.0, "VETERINARIA"),

    # QUIROFANO
    ("ANESTESIA CORTA", "QUIROFANO", 70.0, "PROCEDIMIENTOS"),
    ("CIRUGIA", "QUIROFANO", 500.0, "VETERINARIA"),
    ("DESBRIDAMIENTO CON FRESA DIAMANTE", "QUIROFANO", 60.0, "-"),
    ("DRENAJE DE PERICARDIO", "QUIROFANO", 200.0, "PROCEDIMIENTOS"),
    ("ELECTROBISTURI (QUIR.)", "QUIROFANO", 5.0, "PROCEDIMIENTOS"),
    ("ELECTROCARDIOGRAMA (QUIR.)", "QUIROFANO", 30.0, "PROCEDIMIENTOS"),
    ("ENFERMERO CIRCULANTE (QUIR.)", "QUIROFANO", 20.0, "PROCEDIMIENTOS"),
    ("GUANTES QUIRURGICOS 7,5", "QUIROFANO", 2.0, "VETERINARIA"),
    ("LUMPECTOMIA CANINA", "QUIROFANO", 877.0, "-"),
    ("MAQUINA DE ANESTESIA (QUIR.)", "QUIROFANO", 50.0, "PROCEDIMIENTOS"),
    ("PISTOLA DE NITROGENO", "QUIROFANO", 60.0, "PROCEDIMIENTOS"),
    ("TARTRECTOMIA CANINA", "QUIROFANO", 150.0, "PROCEDIMIENTOS"),

    # SERVICIOS
    ("DESECHOS BIOLOGICOS", "SERVICIOS", 30.0, "AMIVETS"),
]


def seed_catalogo():
    db = SessionLocal()
    try:
        count = db.query(CatalogoServicio).count()
        if count > 0:
            print(f"[i] Catalogo already has {count} records. Skipping seed.")
            return

        print(f"[+] Seeding {len(SERVICIOS)} catalog services...")
        for nombre, categoria, precio_ref, unidad in SERVICIOS:
            s = CatalogoServicio(
                nombre=nombre,
                categoria=categoria,
                precio_ref=precio_ref,
                unidad=unidad,
                activo=True,
            )
            db.add(s)

        db.commit()
        print(f"[+] Done. {len(SERVICIOS)} services inserted into catalogo_servicios.")
    except Exception as e:
        db.rollback()
        print(f"[!] Error seeding catalog: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_catalogo()
