"""Add clinical tabs logic

Revision ID: 8ae206b11dda
Revises: 
Create Date: 2026-03-18 03:08:49.512806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae206b11dda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cirugias', sa.Column('precio_aplicado', sa.Float(), nullable=False))
    op.add_column('cirugias', sa.Column('facturado', sa.Boolean(), nullable=True))
    op.alter_column('citas', 'veterinario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('hospitalizaciones', sa.Column('precio_aplicado', sa.Float(), nullable=False))
    op.add_column('hospitalizaciones', sa.Column('facturado', sa.Boolean(), nullable=True))
    op.add_column('hospitalizaciones', sa.Column('consulta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hospitalizaciones', 'consultas', ['consulta_id'], ['id'])
    op.drop_constraint('mascotas_codigo_historia_key', 'mascotas', type_='unique')
    op.create_index(op.f('ix_mascotas_codigo_historia'), 'mascotas', ['codigo_historia'], unique=True)
    op.create_unique_constraint(None, 'mascotas', ['microchip'])
    op.add_column('pruebas_complementarias', sa.Column('precio_aplicado', sa.Float(), nullable=False))
    op.add_column('pruebas_complementarias', sa.Column('facturado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pruebas_complementarias', 'facturado')
    op.drop_column('pruebas_complementarias', 'precio_aplicado')
    op.drop_constraint(None, 'mascotas', type_='unique')
    op.drop_index(op.f('ix_mascotas_codigo_historia'), table_name='mascotas')
    op.create_unique_constraint('mascotas_codigo_historia_key', 'mascotas', ['codigo_historia'])
    op.drop_constraint(None, 'hospitalizaciones', type_='foreignkey')
    op.drop_column('hospitalizaciones', 'consulta_id')
    op.drop_column('hospitalizaciones', 'facturado')
    op.drop_column('hospitalizaciones', 'precio_aplicado')
    op.alter_column('citas', 'veterinario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cirugias', 'facturado')
    op.drop_column('cirugias', 'precio_aplicado')
    # ### end Alembic commands ###
